services:
  - type: web
    name: real-wealthy-1
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: 
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://uun-rawwealthy.vercel.app/
