services:
  - type: web
    name: real-wealthy-
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://shakebody830_db_user:o5RAVqwVBalorrth@rawwealthy.g29rpm3.mongodb.net/?appName=rawwealthy
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@rawwealthy.com
      - key: ADMIN_PASSWORD
        value: Admin123456
      - key: NODE_ENV
      - key: ADMIN_URL
      - value: https://rawwealthyadmin.netlify.app/
        value: production
      - key: CLIENT_URL
        value: https://i-rawwealthy.vercel.app/
