services:
  - type: web
    name: real-wealthy-1
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://shakebody830_db_user:Om8DH2JlRaHfGkrI@rawwealthy.g29rpm3.mongodb.net/raw_wealthy_prod?retryWrites=true&w=majority&appName=rawwealthy
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@rawwealthy.com
      - key: ADMIN_PASSWORD
        value: Admin123!
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://uun-rawwealthy.vercel.app/
