services:
  - type: web
    name: real-wealthy-1
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://rawwealthy:AhP7sb4ZVSpMURv@rawwealthy.9cnu0jw.mongodb.net/rawwealthy?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://raw-wealthy.vercel.app/
