services:
  - type: web
    name: real-wealthy-
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://loismotion6_db_user:In39BUlOOhidocFO@rawwealthy.tf616kg.mongodb.net/rawwealthy_db?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@rawwealthty.com
      - key: ADMIN_PASSWORD
        value: Admin123456
      - key: NODE_ENV
      - key: ADMIN_URL
      - value: https://uuuuu-rawwealthy.vercel.app/
        value: production
      - key: CLIENT_URL
        value: https://i-rawwealthy.vercel.app/
