services:
  - type: web
    name: real-wealthy-
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://Rawwealthy:x38DUdxo0TpL5tDG@rawwealthy.b9kvlnv.mongodb.net/rawwealthy?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@rawwealthy.com
      - key: ADMIN_PASSWORD
        value: Admin123456
      - key: NODE_ENV
      - key: ADMIN_URL
      - value: https://rawwealthyadmin.netlify.app/
        value: production
      - key: CLIENT_URL
        value: https://mn-rawwealthy.vercel.app/
